config:
  image_grid_width_sm: 640
  image_grid_width_md: 1080
  image_grid_width_lg: 1800
  image_width_sm: 1080
  image_width_md: 1800
  image_width_lg: 2400
  font_stack_system: >-
    -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu,
    Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", Arial, sans-serif,
    "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"
metadata:
  site_url: 'https://kondratov'
  site_title: Pavel Kondratov
  site_subtitle_1: Designer
  site_subtitle_2: 'Saint-Petersburg, Russia'
  site_description: >
    My name is Pavel. I work with 3D graphics, animation, and complex
    three-dimensional scenes.


    My practice is centered around movement, space, and the interaction of light
    within 3D environments, where I primarily use Houdini to explore procedural
    workflows and dynamic systems.


    Alongside my 3D work, I shoot video and photograph on film. Through video, I
    am developing a deeper understanding of visual language and storytelling.
    Film photography, in turn, allows me to slow down and focus on portraiture
    and on people within their surrounding space, paying close attention to the
    moment.


    On this site, I share my film photographs.
  site_email: seetoare@gmail.com
  site_social_url: 'https://t.me/wildproject_log'
  site_icon_svg: /assets/uploads/favicon.svg
  site_icon_png: ''
  site_ga4_id: ''
  seo:
    site_title: Halide - Jamstack portfolio theme
    site_description: >-
      A customizable, minimalist portfolio website designed for photographers
      and still image creators.
    no_index: false
theme:
  theme_layout:
    space_scale: 100
  theme_colors:
    background: '#ffffff'
    text: '#101010'
    link: '#2DCD55'
    background_dark: '#101010'
    text_dark: '#E1E1E1'
    link_dark: '#FFFFFF'
  theme_typography:
    font: Overpass Mono
    font_weight: 400
    font_scale: 100
    line_height_scale: 100
  theme_features:
    enable_dark_mode: true
    item_output_limit: 48
    transition_duration: 300
    show_project_year: true
    show_project_grid_titles: true
images:
  avif:
    enabled: false
  webp:
    enabled: true
    quality: 75
  jpeg:
    enabled: true
    quality: 75
i18n:
  site_language: en
  site_social_title: Telegram
